"""add actor_id and updated_at to feedback

Revision ID: 8f21006b8d2f
Revises: b021de2002f5
Create Date: 2026-01-23 16:45:12.729975
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '8f21006b8d2f'
down_revision: Union[str, None] = 'b021de2002f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('actor_id', sa.String(length=64), nullable=False))
    op.add_column('feedback', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_feedback_actor_id'), 'feedback', ['actor_id'], unique=False)
    op.create_index('ix_feedback_message_id', 'feedback', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_message_id', table_name='feedback')
    op.drop_index(op.f('ix_feedback_actor_id'), table_name='feedback')
    op.drop_column('feedback', 'updated_at')
    op.drop_column('feedback', 'actor_id')
    # ### end Alembic commands ###
