"""add user_role to feedback

Revision ID: fd5cd1a7fa49
Revises: 8f21006b8d2f
Create Date: 2026-01-23 16:58:14.442735
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'fd5cd1a7fa49'
down_revision: Union[str, None] = '8f21006b8d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('user_role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'user_role')
    # ### end Alembic commands ###
